### ISSUE TITLE
relative URIs in oob payload

### ISSUE THREAD

**Issue by reschke** [EricssonResearch/Blind-Cache-Drafts#11]
Relative URIs in the OOB payload make the processing a bit weird - currently used content codings do not need additional information to be processed.

We could easily require the use of absolute URIs, it would only make the special case of the fallback URI more verbose and slightly harder to detect -- the latter could be solved by reintroducing an annotation (now that we have a place for annotations).

That said, the encryption encoding will need additional information as well to be processed; and the same is probably true for the proposed dictionary based compression codings, so maybe this is a non-issue.

**Comment by gaperik** [comment]
OOB encoding is not like other encodings is it, with the payload going one way, the meta data another way and recomposed at the end. Isn't the difference in terms of additional information needed motivated?

That said, the extra burden of using annotation for fallback does not break anyone's back does it? And since it's more than likely that annotations will be there and used for other purposes in the resource map, I propose "go for it" with an annotation for fall back.

**Comment by reschke** [comment]
Not really an issue.
